### ISSUE TITLE
%player% as NPC skin

### ISSUE THREAD

**Issue by The-Gust** [PluginBugs/Issues-CinematicsStudio#10]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Gust#1337

### What happened?

%player% placeholder is not working for skin setting (trying to display cinematic viewer skin).

### Steps to reproduce the issue

1. Create NPC;
2. Set %player% line for skin.

### Server version

Paper 1.19.2 build 307

### CinematicsStudio Version

CinematicsStudio 1.4.3-r5

### ProtocolLib Version

ProtocolLib build 606

### LoneLibs Version

LoneLibs 1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/43398430/215079567-fab3fc60-fbd5-4f89-9404-f8b6f50e5e41.png)

**Comment by LoneDev6** [comment]
Thanks, this will be checked as soon as possible
