### ISSUE TITLE
Full placeholders support + IAEmojis

### ISSUE THREAD

**Issue by Desmordss** [PluginBugs/Issues-CinematicsStudio#13]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

desmoo#3218

### Describe the solution you'd like

Dear lonedev, please add placeholders and emojis support to itemsadder

### Is your feature request related to a problem?

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by LoneDev6** [comment]
Can you specify where you need them to be supported?
In which places of the plugin?

Send screenshots if possible.
