### ISSUE TITLE
API - `CutsceneStopEvent$Cause` issue

### ISSUE THREAD

**Issue by srnyx** [PluginBugs/Issues-CinematicsStudio#14]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

srnyx#0001

### What happened?

When comparing `CutsceneStopEvent#getCause` and a `CutsceneStopEvent$Cause`, my IDE gets a little angry:
> Operator '!=' cannot be applied to 'dev.lone.cinematicstudio.api.events.CutsceneStopEvent.Cause', 'dev.lone.cinematicstudio.api.events.CutsceneStopEvent$Cause'

**THIS IS ONLY VISUAL!** The plugin still compiles and works. The event also works as intended when fired.
This probably means it's more of an IDE issue. However, I think it's a simple fix on your end by just not using the `$` character for `CutsceneStopEvent$Cause`, and instead just naming it `Cause`.

### Steps to reproduce the issue

1. Add `CutsceneStopEvent` event handler
2. Compare a `CutsceneStopEvent$Cause` with `CutsceneStopEvent#getCause`
3. Observe warning

### CinematicsStudio Version

1.4.3-r5

### Screenshots/Videos

![img](https://img.srnyx.xyz/r/0NgARKPqkW.png)

**Comment by LoneDev6** [comment]
Will be checked

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/224753955-c6716f86-4c05-4118-9243-3ddaab4dda62.png)
Works just fine.
```xml
 <dependency>
    <groupId>libs</groupId>
    <artifactId>CinematicStudio</artifactId>
    <version>1.0</version>
    <scope>system</scope>
    <systemPath>your path here/CinematicStudio.jar</systemPath>
</dependency>
```

The $ character you're talking about is just how java handles inner classes.
https://stackoverflow.com/questions/11388840/java-compiled-classes-contain-dollar-signs

**Comment by LoneDev6** [comment]
This might be because of how Proguard handles classes relocation.
I'll provide a fix for this.

**Comment by srnyx** [comment]
> ```
>  <dependency>
>     <groupId>libs</groupId>
>     <artifactId>CinematicStudio</artifactId>
>     <version>1.0</version>
>     <scope>system</scope>
>     <systemPath>your path here/CinematicStudio.jar</systemPath>
> </dependency>
> ```

I'm using Gradle Kotlin DSL, like this:
```kotlin
dependencies {
    compileOnly(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
}
```
And then I have the CinematicStudio JAR file in the `libs` folder. So not sure if that changes anything. *This dependency thing works fine for other APIs/libraries that I have in the `libs` folder too.*

**Comment by LoneDev6** [comment]
Update and check please
