### ISSUE TITLE
Cinematic Studio bug

### ISSUE THREAD

**Issue by Arvinnnnnn** [PluginBugs/Issues-CinematicsStudio#16]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Arvinizdabest#4837

### What happened?

when a player uses /cin play abc for the second time, that player will be kicked

### Steps to reproduce the issue

0

### Server version

git-Purpur-1845 (MC: 1.19.2)

### CinematicsStudio Version

Cinematic Studio 1.4.3-r5

### ProtocolLib Version

protolib v5.0.0-snapshot-b608

### LoneLibs Version

1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-CinematicsStudio/files/10868267/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/97273150/222349401-939419cf-015f-487a-ae88-aba5e954a58a.png)
![image](https://user-images.githubusercontent.com/97273150/222396389-498b0470-1ebb-4132-b699-efadc63129aa.png)
![image](https://user-images.githubusercontent.com/97273150/222396423-fde0db75-92a1-4f77-bae7-f7855e996918.png)

**Comment by LoneDev6** [comment]
Probably your cinematic animation has no camera.
Make sure to create one.

Anyway I'll try to fix this remove in the next update.
