### ISSUE TITLE
%player% Doesn´t work at 1.4.3-r6

### ISSUE THREAD

**Issue by mario638** [PluginBugs/Issues-CinematicsStudio#18]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

![image](https://user-images.githubusercontent.com/86148117/224793409-e186843f-5b8c-4435-ad29-4a3a21a91ab2.png)

### Steps to reproduce the issue

Create a NPC with %player% as skin
Play the cinematic
The skin is steve

### Server version

![image](https://user-images.githubusercontent.com/86148117/224793573-33036f19-da5e-47d1-b85f-b7c1d266d981.png)

### CinematicsStudio Version

1.4.3-r6

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/86148117/224793663-99cba954-fef0-49da-a519-93b27a5a576b.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/86148117/224793703-3fb44785-f0ca-40c1-a2b3-b9fce2b84529.png)

### FULL server log

There is no errors

### Error (optional)

```shell
There is no errors
```

### CinematicsStudio config.yml

```shell
Timeline:
- '30'
- '115'
- '30'
- '0'
- '0'
- '0'
- '0'
- '0'
- '0'
- '0'
- '0'
- '0'
- '0'
- '0'
- '0'
- '0'
cameraTimeline:
- Survival,-54.9621,70.8602,42.4568,18.6967,-89.2178,true,true,true,0
- Survival,-48.346,68.0,42.4589,3.0809,-90.1642,true,false,true,100
- Empty
- Survival,-46.57,68.0,42.53,2.45,90.6,false,true,true,0
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
npcTimeline:
- Spawn,null,AIR,AIR,AIR,AIR,AIR,Survival,-46.57,68.0,42.53,90.6,2.6077,%player%,ewogICJ0aW1lc3RhbXAiIDogMTYxNTIxMTA5NTEzNywKICAicHJvZmlsZUlkIiA6ICJkYmNlZjMyZjI5ZDc0Y2UzOTUzOWMwYjBhMTE1YjZiZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJyYW1waXJlIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2I5MDY5NmViYzc0Y2U3YTkwMGVjOGFiZWVjMGRjMWNjYjM1MzRjMWI4YmE2Y2JkOWU4M2M1Y2Q3ZjM4MWZiNDgiCiAgICB9CiAgfQp9,qJYduRTp7UnuvtApIeEdPeYTny4SQ/PdzMUvJnBaOlauOQlUAWwEvGy/27aTRxRcKIE4B0g11jd2eH8hmQBa/jDd5DtAjAQp8WmNgce5LB9xlfxrlkumR5KwV95tTG3VMxsaNBAUESqrmJTIf76ZY5y4VE0VxTPZhGcr//zQfsyMJa+7TfvniikB6cgEootEcD5WJq5/PlVjbbzIbj0gKatV/gsFdTlnEGbtcFJWXr7vF62vGNKa0qzZDED0f3cjVKl5zQU343ndvF1BOShh2d9pNDsEsedwDHHYKA2MvWFI/AAXLAeVCN2DOqmWy17zvNlZrra/9deOVdO2mojNz55z3TE0Va3UC1QuK1HCK2dEvR/pruSy3ceRHgYc2o82avH8FdUEXPIDGUVOHzeI9yTNgN0/28KvxAKznN3/q28x4NwYXYnscX3Oim2mqQrJSWd3Qa8Z2aktGu87IKQsUkX1vhmHnG9zOVzdYXE1tfe2iYZzyrfSfZLgsz9SZ8dSLzA1rqZHYmAJDr754+3toutva8iSqGETcbg4+01M8LurDipX9oGAlrqgk+DFKvdmgufY1r+lEx4Of/0b3Xx2/LMTAmsLyVlKFF1QsX1gkeMYwdzvs2/xyUtnLEvjmrYW2Xy9f3qRP1wVNZJRquLXTP4AJu8IkkY/CVm4GUi2qT8=,AIR,PLAYER,0
- Recording,0,5
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
effectsTimeline:
- 'Command;titlemsg %player% :negro: -in:1 -keep:30 -out:1'
- 'Command;titlemsg %player% :cinematica: -keep:200'
- 'Command;titlemsg %player% :negro: -in:1 -keep:30 -out:30'
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
soundsTimeline:
- Sound,minecraft:item.chorus_fruit.teleport,1.0,1.0
- Empty
- Empty
- Sound,minecraft:item.chorus_fruit.teleport,1.0,1.0
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
- Empty
ID: 6
Settings:
  CommandsOnEnd:
  - efly %player% disable
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/86148117/224793957-6d95c2b5-b6de-44be-bc84-1a25360c243c.png)

**Comment by LoneDev6** [comment]
About the error, please next time open a new github report, do not post everything in the same issue report.

**Comment by LoneDev6** [comment]
Cannot reproduce on 1.19.4 (upcoming compatibility update)

https://user-images.githubusercontent.com/27242001/229088671-d99f9baf-1fdf-44c1-80a2-a0c3daeaaaf3.mp4

```
[11:55:16 INFO]: CinematicStudio version 1.4.3-r7
[11:55:16 INFO]: Cutscene Tool to create advanced cutscenes
[11:55:16 INFO]: Authors: LoneDev and CraterHater
> version
[11:55:18 INFO]: Checking version, please wait...
[11:55:19 INFO]: This server is running Paper version git-Paper-468 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9087a64)
```
