### ISSUE TITLE
%player% still not working

### ISSUE THREAD

**Issue by mario638** [PluginBugs/Issues-CinematicsStudio#23]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Same as #18 

### Steps to reproduce the issue

Same as #18 

### Server version

Same as #18 

### CinematicsStudio Version

Same as #18 

### ProtocolLib Version

Same as #18 

### LoneLibs Version

Same as #18 

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/86148117/229091687-fee79437-9f44-4873-a6d0-28e3821784a5.png)
I have founded this and in your video is different @LoneDev6

**Comment by LoneDev6** [comment]
Update your plugin please

**Comment by mario638** [comment]
Is updated to the last version at spigot

**Comment by mario638** [comment]
oh you updated now

**Comment by mario638** [comment]
It works

**Comment by LoneDev6** [comment]
Nice
