### ISSUE TITLE
Bug with cinematic on test server

### ISSUE THREAD

**Issue by Weyl1** [PluginBugs/Issues-CinematicsStudio#3]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

SauceDePoulet@0708

### What happened?

I am on your test server and I discovered a bug with the cinematic plugin, when I disconnect during the cinematic, and I reconnect the spawn where I disconnected and not at the end of the cinematic

### Steps to reproduce the issue

1. click button on test server
2. disconnect and reconnect

### Server version

Test server mc.devs.beer

### CinematicsStudio Version

//////////////////////////////////

### ProtocolLib Version

//////////////////////////////////

### LoneLibs Version

//////////////////////////////////

### FULL server log

//////////////////////////////////

### Error (optional)

```shell
//////////////////////////////////
```

### Problematic items yml configuration file (optional)

```shell
//////////////////////////////////
```

### Other files, you can drag and drop them here to upload. (optional)

//////////////////////////////////

### Screenshots/Videos (you can drag and drop files or paste links)

//////////////////////////////////

**Comment by LoneDev6** [comment]
This will be fixed, anyway you're not supposed to be teleported at the end of the cutscene.
The player will be teleported to the previous location of where the they were at the start of the cutscene.
