### ISSUE TITLE
Implement an automatic way to wear the pumpkin on cutscene start

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-CinematicsStudio#30]
https://lonedev.gitbook.io/cinematicstudio/special-effects

**Comment by Desmordss** [comment]
I suggest adding the ability to put on or pick up any item/armor in the cutscene (including with CustomModelData)

**Comment by Desmordss** [comment]
or be able to create custom inventory, for example, to show players story cutscenes

**Comment by LoneDev6** [comment]
Will be implemented as soon as I can find the time.
Thanks for the patience.

**Comment by LoneDev6** [comment]
Will be added:


![Image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/27242001/bb5d8061-1f45-4b4f-919d-01745a11b3d0)

**Comment by Mike5357** [comment]
Is it possible to set the CustomModelData of the pumpkin as suggested?

**Comment by LoneDev6** [comment]
No, I opened a request: https://github.com/PluginBugs/Issues-CinematicsStudio/issues/49
