### ISSUE TITLE
middle click

### ISSUE THREAD

**Issue by erha8** [PluginBugs/Issues-CinematicsStudio#39]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

in the newer versions of minecraft you cannot detect a middle click, however the plugin still uses it, for example "middle click to edit". I find this very irritating, because I **really** need those features which I currently cannot use.

### Steps to reproduce the issue

NPC example:
add a new npc
hover over the painting
in the lore of the item, it states "Middle click to set a skin"

### Server version

![image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/105505339/f9f952a7-9c1d-4616-ac63-a5261aff3112)

### CinematicsStudio Version

![image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/105505339/0e92eae3-b8ee-4d23-a563-6889312a8773)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/105505339/995004af-1fe2-46c4-ba78-c974523a33b2)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/105505339/e8a90116-c5cf-4b16-a09f-e39fdd0f1ed7)

### FULL server log

This issue has nothing to do with logs

### CinematicsStudio config.yml

```shell
my config is empty...
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-CinematicsStudio/assets/105505339/1859091c-8172-402d-87ba-690f32b883e7

**Comment by LoneDev6** [comment]
If you switch to creative mode you should be able to middleclick, let me know.

**Comment by erha8** [comment]
I have tried this(as you can see in the video), but with no success...

**Comment by LoneDev6** [comment]
I'll do some tests, probably Mojang totally removed the middleclick feature, anyway last time I checked it was working fine.
I'll keep you updated.

**Comment by LoneDev6** [comment]
Test with a vanilla client, make sure it's not a mod or plugin interfering.

I tested on Minecraft 1.20.1 and 1.18.2.
Middle click works both in creative and survival.
(both vanilla game and modded with [fabulously-optimized modpack](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized))



https://github.com/PluginBugs/Issues-CinematicsStudio/assets/27242001/331b13cc-e501-405e-9e4a-aeae641146df
