### ISSUE TITLE
Perform some work at the end

### ISSUE THREAD

**Issue by inrhor** [PluginBugs/Issues-CinematicsStudio#4]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Perform some work at the end, such as transferring a location

### Is your feature request related to a problem?

none

### Describe alternatives you've considered

none

**Comment by LoneDev6** [comment]
You can do it via commands. Add a new teleport command at the cinematic end.
