### ISSUE TITLE
Open the editing screen after playback

### ISSUE THREAD

**Issue by inrhor** [PluginBugs/Issues-CinematicsStudio#5]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

When I open the edit gui, it forces the edit gui to open every time I play.

### Steps to reproduce the issue

1.When I open the edit gui
2.it forces the edit gui to open every time I play

### Server version

Purpur-1.18.2

### CinematicsStudio Version

1.4.3-r4

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.21

**Comment by Mike5357** [comment]
Bump; this issue makes the plugin unusable.

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
The cinematic editing GUI is opened only when you run the cinematic using the cinematic editing GUI, it's normal because you usually want to play it multiple times during editing.

The command won't open the editing GUI after cinematic end.
