### ISSUE TITLE
Add again %player% to see the player skin

### ISSUE THREAD

**Issue by mario638** [PluginBugs/Issues-CinematicsStudio#6]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

mario638#2828

### Describe the solution you'd like

Add again %player% to see the player skin

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

No

**Comment by LoneDev6** [comment]
This is unclear, I have no idea what you're trying to request

**Comment by mario638** [comment]
Lonedev I mean that in the old version of the old autor of the plugin there was a placeholder to see the sking of the player watching like you see your skin and other players see their skin

**Comment by mario638** [comment]
And so much thinks that are in the old version can you pls added it back and old cinematic merger
