### ISSUE TITLE
/effect not working

### ISSUE THREAD

**Issue by NuggetDesign** [PluginBugs/Issues-CinematicsStudio#7]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

I can't get /effect to work in a cinematic scene. I'm trying to give it a zoom effect

### Steps to reproduce the issue

1. add effect give %playername% minecraft:slowness 10 4 to a scene
2. start the scene
3. result - the effect will be applied after its completed.

### Server version

This server is running Paper version git-Paper-282 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e6e37ba)

### CinematicsStudio Version

CinematicStudio version 1.4.3-r4

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b608

### LoneLibs Version

LoneLibs version 1.0.22

### FULL server log

https://paste.helpch.at/otujinihed.makefile

### CinematicsStudio config.yml

```shell
The config file can't be open
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Screenshot 2023-01-05 144030](https://user-images.githubusercontent.com/75328554/210727144-e3219591-2fe6-4950-8588-258780624a24.png)

![Screenshot 2023-01-05 144058](https://user-images.githubusercontent.com/75328554/210727230-e484f054-a956-4874-926e-6ac2e890075a.png)

**Comment by LoneDev6** [comment]
Show your timeline

**Comment by NuggetDesign** [comment]
> Show your timeline

What do you mean by that.

**Comment by LoneDev6** [comment]
The timeline
https://lonedev.gitbook.io/cinematicstudio/interface
![image](https://user-images.githubusercontent.com/27242001/211542157-03d8f4d0-1653-4ace-aa5e-d3d77cfdba82.png)

**Comment by NuggetDesign** [comment]
Hello sorry about the delay, I'm working on a new project. Here is the timeline
![image](https://user-images.githubusercontent.com/75328554/228467674-7972bbfa-2097-41c7-b27f-1e9543a867d9.png)

**Comment by LoneDev6** [comment]
Works fine for me

https://user-images.githubusercontent.com/27242001/229094517-d3eabd68-8897-4d90-8dac-c8f66b285c50.mp4

```
[12:21:44 INFO]: Checking version, please wait...
[12:21:44 INFO]: This server is running Paper version git-Paper-468 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9087a64)
You are 15 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-466 (MC: 1.19.4)
> version CinematicStudio
[12:21:48 INFO]: CinematicStudio version 1.4.3-r7
[12:21:48 INFO]: Cutscene Tool to create advanced cutscenes
[12:21:48 INFO]: Authors: LoneDev and CraterHater
```

**Comment by NuggetDesign** [comment]
The command /effect doesnt work like it use to before. The effects you're using is the default ones that is provided via the effects. 

This used to work before.

**Comment by NuggetDesign** [comment]
Try command /effect slow with the level 4

**Comment by LoneDev6** [comment]
can't reproduce.

https://github.com/PluginBugs/Issues-CinematicsStudio/assets/27242001/30da8ad9-ecae-48d5-ae48-9f80b805180d

**Comment by NuggetDesign** [comment]
> can't reproduce.
> 
> 
> 
> https://github.com/PluginBugs/Issues-CinematicsStudio/assets/27242001/30da8ad9-ecae-48d5-ae48-9f80b805180d
> 
> 
> 
> 

How about for slowness, it works?

**Comment by LoneDev6** [comment]
You can't make the camera slower using a potion effect.
Slow down the movement making a larger distance between the point A and B and set the two keyframes far from each other in the timeline.

**Comment by NuggetDesign** [comment]
> You can't make the camera slower using a potion effect.
> 
> Slow down the movement making a larger distance between the point A and B and set the two keyframes far from each other in the timeline.

Not trying to make it slow. The slow effect makes the camera zoom
